language: node_js
dist: xenial
node_js:
- "8"
services:
- docker
- xvfb
before_install:
  # Updating NPM to relevant version >= 3 on Node.JS LTS
- npm i -g brfs
script:
- npm run lint
- npm run build-prod
sudo: required
addons:
  apt:
    packages:
    - sshpass
    - google-chrome-stable

